Fix overloaded virtual (#21)
* Handle deprecation of std::iterator in C++17

See f.e.:
  https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/

* Fix dangling pointer to an unnamed temporary error

error: dangling pointer to an unnamed temporary may be used [-Werror=dangling-pointer=]

* Fix compile error -Werror=overloaded-virtual

---------

Co-authored-by: Raoul <noreply@undefined.home.arpa>
Co-authored-by: Arne Köhn <arne@chark.eu>