Fix windows cross-compilation linking errors
Changes to the linking when cross compiling to windows:
* Adds gdiplus
* Adds libfltk_png.a
* Adds libfltk_z.a
* Removes unneeded libfltk_images.a

The fltk additions fix these linking errors:

    /usr/bin/x86_64-w64-mingw32-ld: burrtools.exe.p/src_gui_image.cpp.obj: in function `image_c::saveToPNG(char const*) const':
    /burr-tools/build-win/../src/gui/image.cpp:140:(.text+0x6aa): undefined reference to `fltk_png_create_write_struct'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:144:(.text+0x6d4): undefined reference to `fltk_png_destroy_write_struct'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:149:(.text+0x711): undefined reference to `fltk_png_create_info_struct'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:153:(.text+0x73b): undefined reference to `fltk_png_destroy_write_struct'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:158:(.text+0x788): undefined reference to `fltk_png_set_longjmp_fn'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:170:(.text+0x827): undefined reference to `fltk_png_destroy_write_struct'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:175:(.text+0x868): undefined reference to `fltk_png_init_io'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:176:(.text+0x8ad): undefined reference to `fltk_png_set_IHDR'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:186:(.text+0x8bd): undefined reference to `fltk_png_write_info'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:204:(.text+0xa7c): undefined reference to `fltk_png_write_image'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:211:(.text+0xaf0): undefined reference to `fltk_png_write_end'
    /usr/bin/x86_64-w64-mingw32-ld: /burr-tools/build-win/../src/gui/image.cpp:213:(.text+0xb00): undefined reference to `fltk_png_destroy_write_struct'

gdiplus is the windows graphics libraries needed by mingw. Adding it
fixes these linking errors:

    /usr/bin/x86_64-w64-mingw32-ld: subprojects/fltk/libfltk.a(src_drivers_WinAPI_fl_WinAPI_platform_init.cxx.obj): in function `Fl_Graphics_Driver::newMainGraphicsDriver()':
    /burr-tools/build-win/../subprojects/fltk/src/drivers/WinAPI/fl_WinAPI_platform_init.cxx:39:(.text+0xff): undefined reference to `GdiplusStartup'
    /usr/bin/x86_64-w64-mingw32-ld: subprojects/fltk/libfltk.a(src_drivers_GDI_Fl_GDI_Graphics_Driver.cxx.obj): in function `Fl_GDIplus_Graphics_Driver::shutdown()':
    /burr-tools/build-win/../subprojects/fltk/src/drivers/GDI/Fl_GDI_Graphics_Driver.cxx:61:(.text+0x2a4): undefined reference to `GdiplusShutdown'
    /usr/bin/x86_64-w64-mingw32-ld: subprojects/fltk/libfltk.a(src_drivers_GDI_Fl_GDI_Graphics_Driver.cxx.obj): in function `Gdiplus::GdiplusBase::operator new(unsigned long long)':
    /usr/share/mingw-w64/include/gdiplus/gdiplusbase.h:38:(.text$_ZN7Gdiplus11GdiplusBasenwEy[_ZN7Gdiplus11GdiplusBasenwEy]+0x14): undefined reference to `GdipAlloc'
    /usr/bin/x86_64-w64-mingw32-ld: subprojects/fltk/libfltk.a(src_drivers_GDI_Fl_GDI_Graphics_Driver.cxx.obj): in function `Gdiplus::GdiplusBase::operator delete(void*)':
    /usr/share/mingw-w64/include/gdiplus/gdiplusbase.h:46:(.text$_ZN7Gdiplus11GdiplusBasedlEPv[_ZN7Gdiplus11GdiplusBasedlEPv]+0x14): undefined reference to `GdipFree'
    /usr/bin/x86_64-w64-mingw32-ld: subprojects/fltk/libfltk.a(src_drivers_GDI_Fl_GDI_Graphics_Driver.cxx.obj): in function `Gdiplus::Brush::~Brush()':
    /usr/share/mingw-w64/include/gdiplus/gdiplusbrush.h:46:(.text$_ZN7Gdiplus5BrushD2Ev[_ZN7Gdiplus5BrushD2Ev]+0x26): undefined reference to `GdipDeleteBrush'
    /usr/bin/x86_64-w64-mingw32-ld: subprojects/fltk/libfltk.a(src_drivers_GDI_Fl_GDI_Graphics_Driver.cxx.obj): in function `Gdiplus::Brush::~Brush()':
    ...